# Generated by Django 4.1.7 on 2023-02-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='email',
        ),
    ]
