# Generated by Django 4.1.7 on 2023-04-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tutoringsession',
            name='start_time_before_end_time',
        ),
    ]
