# Generated by Django 4.1.7 on 2023-05-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tutoringrequest',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_request_per_session'),
        ),
    ]
