# Generated by Django 4.1.7 on 2023-05-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0002_tutoringrequest_unique_request_per_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
