# Generated by Django 4.1.7 on 2023-04-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0002_alter_tutor_hourly_rate_tutoringsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringsession',
            name='time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tutoringsession',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
