# Generated by Django 4.1.7 on 2023-02-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0003_student_verify_student_student_verify_tutor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='verify_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verify_tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='verify_student',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='verify_tutor',
        ),
    ]
