# Generated by Django 4.1.7 on 2023-04-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0004_tutoringrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tutoringrequest',
            name='message',
            field=models.TextField(default='', max_length=200),
        ),
    ]
