# Generated by Django 4.1.7 on 2023-03-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0006_tutorclasses_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classes',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
