# Generated by Django 4.1.7 on 2023-04-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0008_studentclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='hourly_rate',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='classes',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='classes',
            field=models.TextField(default='', max_length=500),
        ),
    ]
