# Generated by Django 4.1.7 on 2023-04-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0009_tutor_hourly_rate_alter_student_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='year',
            field=models.IntegerField(),
        ),
    ]
