# Generated by Django 4.1.7 on 2023-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0010_alter_tutor_hourly_rate_alter_tutor_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='hourly_rate',
            field=models.TextField(default='', max_length=500),
        ),
    ]
