# Generated by Django 4.1.7 on 2023-04-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0012_alter_tutor_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random',
            field=models.TextField(default='', max_length=500),
        ),
    ]
